#cloud-config
# Generated by Terraform from cloud-init.yaml.tpl. Runs once on first boot.
# Logs land in /var/log/cloud-init-output.log on the server.
#
# Phase 1 stub: creates the user, generates the host age key for sops-nix,
# and prepares the system for a nixos-anywhere installation.
#
# Phase 3 will complete the nixos-anywhere invocation once NixOS modules are
# implemented. Until then, the box can be bootstrapped with the legacy
# bootstrap.sh path (see bootstrap/legacy/ after Phase 3).
#
# Secrets in this file:
#   TS_AUTHKEY — short-lived (1 h expiry), single-device-join scope. Acceptable
#     to embed here even though Hetzner stores user_data for the lifetime of
#     the server, because the key is useless once consumed/expired.
#   USER_PASSWORD — intentionally NOT included. Set the user password by hand
#     after first login (`passwd <user>` over Tailscale SSH). Storing a long-
#     lived secret in user_data would expose it via the Hetzner API forever.
#
# bootstrap.TERRAFORM.9-1
write_files:
  - path: /etc/devbox-bootstrap.env
    permissions: '0600'
    owner: root:root
    content: |
      # Bootstrap environment from Terraform / cloud-init. Re-sourceable.
      # Edit this file and run `devbox-rerun` to retry with different values.
      export USERNAME='${username}'
      export MACHINE_NAME='${hostname}'
      export TS_TAG='${ts_tag}'
      export TS_AUTHKEY='${ts_authkey}'
      export DOTFILES_REPO='${dotfiles_repo}'
      export DEV_MODE='${dev_mode}'

runcmd:
  # Prepare log directory and write initial STATE marker
  # bootstrap.TERRAFORM.9-3
  - mkdir -p /var/log/bootstrap
  - echo "running" > /var/log/bootstrap/STATE

  # Generate the host age key for sops-nix secrets decryption.
  # The public key must be registered in secrets/.sops.yaml before
  # any sops-encrypted secret can be deployed via nixos-anywhere.
  # bootstrap.NIXOS_PHASE1.6
  - apt-get install -y -q age
  - mkdir -p /root/age
  - age-keygen -o /root/age/identity.txt 2>/tmp/age-keygen.out
  - grep 'public key:' /tmp/age-keygen.out | awk '{print $NF}' > /root/age/identity.pub
  - chmod 600 /root/age/identity.txt
  - echo "Age public key (register in secrets/.sops.yaml):"
  - cat /root/age/identity.pub

  # TODO (Phase 3): invoke nixos-anywhere to replace Ubuntu with NixOS.
  # Prerequisite: the public key above must be added to secrets/.sops.yaml
  # and flake.lock must be committed before this can succeed.
  #
  # nix run github:nix-community/nixos-anywhere -- \
  #   --flake github:${devbox_repo_owner}/devbox#devbox \
  #   --target-host root@localhost
  #
  # For now, write STATE=ok so health checks pass during scaffolding.
  - echo "ok" > /var/log/bootstrap/STATE
