#cloud-config
# Generated by Terraform from cloud-init.yaml.tpl. Runs once on first boot.
# Logs land in /var/log/cloud-init-output.log on the server.
#
# Secrets in this file:
#   TS_AUTHKEY — short-lived (1 h expiry), single-device-join scope. Acceptable
#     to embed here even though Hetzner stores user_data for the lifetime of
#     the server, because the key is useless once consumed/expired.
#   USER_PASSWORD — intentionally NOT included. Set the user password by hand
#     after first login (`passwd <user>` over Tailscale SSH). Storing a long-
#     lived secret in user_data would expose it via the Hetzner API forever.
package_update: true
packages:
  - git
runcmd:
  - mkdir -p /root/projects
  - git clone ${devbox_repo} /root/projects/devbox
  - |
    cd /root/projects/devbox && \
    USERNAME='${username}' \
    MACHINE_NAME='${hostname}' \
    TS_TAG='${ts_tag}' \
    TS_AUTHKEY='${ts_authkey}' \
    DOTFILES_REPO='${dotfiles_repo}' \
    bash bootstrap/bootstrap.sh
